# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 11:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
