# Generated by Django 3.0.5 on 2020-04-22 03:04

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20161231_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='workflow_state',
            field=django_fsm.FSMField(default='draft', max_length=50),
        ),
    ]
